[package]
name = "ridl-impl"
version = "0.0.1"
edition = "2021"

[dependencies]
inventory = "0.3.19"
pyo3 = { version = "0.23.4", features = ["abi3-py38"], optional = true }

[features]
py = ["dep:pyo3"]
